# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdd352278e90159104bacb822527f7aa63f72cadeb51770ad8659778cd574abe8f681c0abea2112cd9ffeac95ff93f6b1f279dbd535ac5ed3eba7bb28864b933

test:
  secret_key_base: a0e02770b15be18a1091b45f21fe0bbc1965c5696e11934f52677ea2344a4b2ebb35a803b886e1ae3c21ecf3aa2381859dba0d1e58d738e38c885b16efea6aa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
