extends:
  - eslint:recommended

plugins:
  - import    # eslint-plugin-import

settings:
  import/resolver:
    node:
      paths:
        - app/assets/javascripts
  import/extensions: [".js"]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2

rules:
  import/no-unresolved: 2

env:
  browser: true
  mocha: true
  node: true
  jquery: true

parserOptions:
  sourceType: module
